name: deploy

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: altinukshini/deployment-action@releases/v1
        with:
          token: "${{ github.token }}"
          environment: production
