name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peter-evans/create-deployment@v3
        with:
          ref: ${{ github.sha }}
          environment: production
          transient_environment: false
          auto_merge: false